workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_WORKSPACE: "ios-theMealsApp.xcworkspace" # Isikan nama project Anda.
          XCODE_SCHEME: "ios-theMealsApp" # Isikan nama scheme project Anda.
    scripts:
      - name: Build Main App
        script: |
          xcodebuild \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          SKIP_UNIT_TESTS=YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - mfahmiardiyannto@gmail.com # Isikan email untuk notifikasi status build
